---
development:
  dialect: postgres
  database: postgres
  user: postgres
  password: example
  host: db_dev
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/real_estate_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/real_estate_production?sslmode=disable"}}
