version: '3.7'

volumes:
  database_data:
    driver: local

services:
  db:
    image: 'arm64v8/postgres:10.21-alpine3.16'
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - database_data:/var/lib/postgresql/data
  api:
    build: ../..
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    env_file:
      - ./database.env